jobs:
  - job: Test
    pool:
      vmImage: 'Ubuntu 16.04'
    variables:
      NODE_VERSION: 12.16.1
      SPRING_OUTPUT_ANSI_ENABLED: NEVER
      SPRING_JPA_SHOW_SQL: false
      JHI_DISABLE_WEBPACK_LOGS: true
      NG_CLI_ANALYTICS: 'false'

    steps:
      #----------------------------------------------------------------------
      # Tests
      #----------------------------------------------------------------------
      - script: |
          chmod +x mvnw
          ./mvnw -ntp checkstyle:check
          ./mvnw -ntp clean verify -P-webpack
        displayName: 'TESTS: backend'
      - script: ./mvnw -ntp verify -Pprod -DskipTests
        displayName: 'TESTS: packaging'
